###############################################################################
# Created by write_sdc
###############################################################################
current_design axi_npu_fabric_macro
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 20.0 [get_ports {clk}]
set_clock_transition 0.1000 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_arready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_arready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_bvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_bvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rdata[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rdata[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_araddr[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_araddr[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_arprot[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_arprot[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_arprot[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_arprot[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_arprot[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_arprot[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_arvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_arvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awaddr[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awaddr[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awprot[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awprot[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awprot[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awprot[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awprot[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awprot[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_bready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_bready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wdata[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wdata[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wstrb[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wstrb[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wstrb[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wstrb[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wstrb[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wstrb[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wstrb[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wstrb[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_irq_done}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_irq_done}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdata[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdata[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_rdy}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_rdy}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_araddr[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_araddr[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_arprot[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_arprot[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_arprot[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_arprot[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_arprot[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_arprot[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_arvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_arvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awaddr[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awaddr[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awprot[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awprot[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awprot[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awprot[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awprot[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awprot[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_awvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_awvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_bready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_bready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_rready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_rready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wdata[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wdata[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wstrb[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wstrb[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wstrb[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wstrb[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wstrb[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wstrb[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wstrb[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wstrb[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {ext_axi_wvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {ext_axi_wvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {irq_done}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {irq_done}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_arready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_arready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_awready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_awready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_bvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_bvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rdata[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rdata[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_rvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_rvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {m_axi_wready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {m_axi_wready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_addr[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_addr[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_vld}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_vld}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_wdata[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_wdata[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {npu_we}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {npu_we}]
set_false_path\
    -from [get_ports {resetn}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0500 [get_ports {ext_axi_arvalid}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awvalid}]
set_load -pin_load 0.0500 [get_ports {ext_axi_bready}]
set_load -pin_load 0.0500 [get_ports {ext_axi_rready}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wvalid}]
set_load -pin_load 0.0500 [get_ports {irq_done}]
set_load -pin_load 0.0500 [get_ports {m_axi_arready}]
set_load -pin_load 0.0500 [get_ports {m_axi_awready}]
set_load -pin_load 0.0500 [get_ports {m_axi_bvalid}]
set_load -pin_load 0.0500 [get_ports {m_axi_rvalid}]
set_load -pin_load 0.0500 [get_ports {m_axi_wready}]
set_load -pin_load 0.0500 [get_ports {npu_vld}]
set_load -pin_load 0.0500 [get_ports {npu_we}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[31]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[30]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[29]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[28]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[27]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[26]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[25]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[24]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[23]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[22]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[21]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[20]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[19]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[18]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[17]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[16]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[15]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[14]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[13]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[12]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[11]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[10]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[9]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[8]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[7]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[6]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[5]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[4]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[3]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[2]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[1]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_araddr[0]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_arprot[2]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_arprot[1]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_arprot[0]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[31]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[30]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[29]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[28]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[27]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[26]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[25]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[24]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[23]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[22]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[21]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[20]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[19]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[18]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[17]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[16]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[15]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[14]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[13]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[12]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[11]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[10]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[9]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[8]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[7]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[6]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[5]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[4]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[3]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[2]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[1]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awaddr[0]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awprot[2]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awprot[1]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_awprot[0]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[31]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[30]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[29]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[28]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[27]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[26]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[25]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[24]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[23]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[22]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[21]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[20]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[19]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[18]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[17]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[16]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[15]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[14]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[13]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[12]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[11]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[10]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[9]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[8]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[7]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[6]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[5]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[4]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[3]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[2]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[1]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wdata[0]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wstrb[3]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wstrb[2]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wstrb[1]}]
set_load -pin_load 0.0500 [get_ports {ext_axi_wstrb[0]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[31]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[30]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[29]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[28]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[27]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[26]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[25]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[24]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[23]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[22]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[21]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[20]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[19]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[18]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[17]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[16]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[15]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[14]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[13]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[12]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[11]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[10]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[9]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[8]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[7]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[6]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[5]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[4]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[3]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[2]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[1]}]
set_load -pin_load 0.0500 [get_ports {m_axi_rdata[0]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[31]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[30]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[29]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[28]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[27]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[26]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[25]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[24]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[23]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[22]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[21]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[20]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[19]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[18]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[17]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[16]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[15]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[14]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[13]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[12]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[11]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[10]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[9]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[8]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[7]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[6]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[5]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[4]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[3]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[2]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[1]}]
set_load -pin_load 0.0500 [get_ports {npu_addr[0]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[31]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[30]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[29]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[28]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[27]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[26]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[25]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[24]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[23]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[22]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[21]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[20]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[19]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[18]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[17]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[16]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[15]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[14]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[13]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[12]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[11]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[10]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[9]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[8]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[7]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[6]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[5]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[4]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[3]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[2]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[1]}]
set_load -pin_load 0.0500 [get_ports {npu_wdata[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 15.0000 [current_design]
